// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package xdpwall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfIpsetDirection uint32

const (
	bpfIpsetDirectionSRC  bpfIpsetDirection = 1
	bpfIpsetDirectionDST  bpfIpsetDirection = 2
	bpfIpsetDirectionBOTH bpfIpsetDirection = 3
)

type bpfIpsetItem struct {
	Addr uint32
	Mask uint32
}

type bpfIpsets struct{ Items [255]bpfIpsetItem }

type bpfProtocol uint32

const (
	bpfProtocolICMP bpfProtocol = 1
	bpfProtocolUDP  bpfProtocol = 17
	bpfProtocolTCP  bpfProtocol = 6
)

type bpfRuleItem struct {
	Enable          int32
	_               [4]byte
	Pkts            uint64
	Bytes           uint64
	Target          bpfTarget
	Protocol        bpfProtocol
	Source          uint32
	SourceMask      uint32
	Destination     uint32
	DestinationMask uint32
	MatchExt        struct {
		Enable int32
		Set    struct {
			Enable    int32
			Id        uint32
			Direction bpfIpsetDirection
		}
		Udp struct {
			Enable int32
			Sport  uint16
			Dport  uint16
		}
		Tcp struct {
			Enable int32
			Sport  uint16
			Dport  uint16
		}
		Multiport uint16
		_         [2]byte
	}
	TargetExt struct{}
	_         [4]byte
}

type bpfRules struct {
	Items [100]bpfRuleItem
	Count int32
	_     [4]byte
}

type bpfTarget uint32

const (
	bpfTargetABORTED bpfTarget = 0
	bpfTargetDROP    bpfTarget = 1
	bpfTargetACCEPT  bpfTarget = 2
	bpfTargetTX      bpfTarget = 3
	bpfTargetFORWARD bpfTarget = 4
	bpfTargetLOG     bpfTarget = 5
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpWallFunc *ebpf.ProgramSpec `ebpf:"xdp_wall_func"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	IpsetMap *ebpf.MapSpec `ebpf:"ipset_map"`
	RuleMap  *ebpf.MapSpec `ebpf:"rule_map"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	IpsetMap *ebpf.Map `ebpf:"ipset_map"`
	RuleMap  *ebpf.Map `ebpf:"rule_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.IpsetMap,
		m.RuleMap,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpWallFunc *ebpf.Program `ebpf:"xdp_wall_func"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpWallFunc,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
